- generic-helpers/src/test/java/io/elimu/a2d2/helpers/PasswordDecryptTest.java
Updated test condition to require "jasypt_encryptor_password"
> GT-68: Added test condition to PasswordDecryptTest

- a2d2-api/src/main/java/io/elimu/a2d2api/RequestInterceptor.java
the file was added after branching out to GitHub
> Added RequestInterceptor to handle HTTP OPTIONS call

- a2d2-api/pom.xml
- a2d2-api/src/main/java/io/elimu/utils/CorrelationInterceptor.java
Added CorrelationInterceptor and adjusted pom dependency.
> Removed java-commons dependency by adding required class to a2d2

- a2d2-api/src/main/java/io/elimu/cdshookapi/api/rest/ServiceProcessController.java
- a2d2-api/src/main/java/io/elimu/cdshookapi/api/rest/TaskEventsController.java
- cds-hook-model/src/main/java/io/elimu/a2d2/process/ServiceUtils.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelperBase.java
- generic-helpers/pom.xml
- generic-helpers/src/main/java/io/elimu/a2d2/helpers/PasswordDecryptUtil.java
- generic-helpers/src/main/java/io/elimu/a2d2/helpers/WIHInvoker.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/MavenJarResolver.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/RunningServices.java
- kie-based-services/src/main/java/io/elimu/serviceapi/service/AbstractKieService.java
- kie-based-services/src/main/java/io/elimu/serviceapi/service/ServiceStore.java
Update code to Throw a dedicated exception instead of using a generic one
Updated code to use unused private fields
Caught Exception instead of Throwable
Defined and used a constant instead of duplicating literals
> Mitigate sonarqube detected bugs

- a2d2-api/pom.xml
@kevinliuelimu  check if this fixes the issues when starting a2d2-api
> Attempted fixes to inter-dependency crashes

- a2d2-api/pom.xml
Updated MySQL connector version to use spring boot managed version
> MySQL connector version update

- a2d2-api/pom.xml
> Added missing property to a2d2-api

- a2d2-api/src/test/java/io/elimu/a2d2/processtest/GenericServiceTest.java
- a2d2-api/src/test/java/io/elimu/a2d2/processtest/GenericTestUtils.java
- a2d2-api/src/test/java/io/elimu/serviceapi/service/MemoryComsumptionTest.java
Updated MemoryComsumptionTest.java and GenericTestUtils for providing runtime mock service.
> Updated testcases

- cds-hook-model/pom.xml
- cds-hook-services/pom.xml
- cdshooks-wih/pom.xml
- core-dependencies/datafetch-service/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- core-wih/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-resource-wih/pom.xml
- ftl-transform-wih/pom.xml
- generic-helpers/pom.xml
- kie-based-services/pom.xml
- pom.xml
- service-daos/pom.xml
- sms-wih/pom.xml
Add the maven enforcer plugin in the a2d2 parent pom.xml file also fix the dependency convergence errors in the project.
> Added maven enforcer plugin for a2d2

- cds-hook-model/src/main/java/io/elimu/a2d2/oauth/BodyBuilder.java
- cds-hook-model/src/main/java/io/elimu/a2d2/oauth/OAuthUtils.java
- core-wih/src/main/java/io/elimu/a2d2/corewih/OAuth2WorkItemHandler.java
- core-wih/src/test/java/io/elimu/a2d2/core_wih/OAuth2WIHTest.java
- fhir-query-helper-base/pom.xml
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelperBase.java
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-r4/pom.xml
- pom.xml
This PR has an implementation to request a token from an OAuth 2.0 source
> OAuth 2.0 get token work item handler implementation

- Dockerfile
- build a2d2-api.war from container
- use openjdk:8-alpine (need to install curl ) as the final container to reduce size
> Updated Dockerfile for multi-stage, used alpine as final container

- a2d2-api/src/main/java/io/elimu/utils/CorrelationInterceptor.java
- core-wih/src/test/java/io/elimu/a2d2/core_wih/ServiceSoapAPIDelegateTest.java
- fhir-query-helper-dstu2/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperTest.java
This PR adds the header X-Correlation-ID as part of the logs and the HTTP response
> X-Correlation-ID adding to the response

- a2d2-api/src/main/java/io/elimu/cdshookapi/api/rest/StatusController.java
Turns out the request must not return 503 when it is still starting up, but not reply at all. This updated implementation takes care of that. Also, due to A2D2's self contained nature, when any service fails we should start returning 503 (after all services have tried to start)
> Updated StatusController

- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericDebugListener.java
GenericDebugListener was missing a null-check
> GenericDebugListener was missing a null-check

- Dockerfile
- a2d2-api/pom.xml
- a2d2-api/src/main/resources/application.yml
Updated mysql connector to 8.0.21.
Updated docker base image to openjdk:11.0-jdk-stretch.
Local Tests passed.
> Updated mysql driver and docker base image to openjdk:11.0-jdk-stretch

- fhir-resource-wih/pom.xml
- kie-based-services/pom.xml
rollback cxf-core-3.3.11.jar as it does not pass the latest maven dependency check
> Reverted cxf-core to its previous version 3.2.14

- Dockerfile
> GT-469:Need a smaller docker base image for a2d2

- a2d2-api/pom.xml
- generic-helpers/pom.xml
- generic-helpers/src/main/java/io/elimu/a2d2/helpers/DateUtil.java
- generic-helpers/src/test/java/io/elimu/a2d2/helpers/DateUtilTest.java
- pom.xml
Needed to displace provided values using timezones
> TimeZone utility methods

- a2d2-api/src/main/java/io/elimu/a2d2api/A2D2Application.java
Needed to start in openshift on separate nodes.
> BT-389 needed to make sure BTM logs are always unique by node

- generic-helpers/src/test/java/io/elimu/a2d2/helpers/DateUtilTest.java
Tries to find a timezone that isn't matching the same offset
> TimeZone test fix

- cds-hook-services/pom.xml
- kie-based-services/src/main/java/io/elimu/genericapi/service/RunningServices.java
Done with mitigating ant  dependency vulnerability
Done with clean and build application and generate report, 
Done with test it on local using curl,
> GT-484 mitigate ant dependency vulnerablity

- a2d2-api/pom.xml
Done with mitigating jakarta.el dependency for a2d2,
Done with build and test locally
> GT-519-mitigate-jakarta.el-dependency-vulnerability

- a2d2-api/pom.xml
Done with mitigate vulnerability of springfox-swagger-ui from a2d2-api
Done with build, ran and test on local
> mitigate springfox-swagger-ui vulnerability

- a2d2-api/src/main/java/io/elimu/cdshookapi/api/rest/docs/SwaggerConfig.java
Fixes regarding failure
tested locally
> a2d2-qa-failure-fixes

- a2d2-api/pom.xml
Done with mitigate vulnerability,
Done with ran docker image on local, test the application successfully
> mitigate commons io vulnerability

- a2d2-api/pom.xml
Done with mitigate tomcat embed code vulnerability,
Done with build and ran a2d2 and omnibus on local
> Mitigate tomcat embed core vulnerability

- a2d2-api/pom.xml
Done with mitigate vulnerability
Done with build, ran and test locally
> mitgate log4j api vulnerablity

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- ftl-transform-wih/pom.xml
- kie-based-services/pom.xml
- pom.xml
- task-utilities/pom.xml
> Updates maven-core dependencies and associated sub-deps

- a2d2-api/pom.xml
Done with mitigate micro-profile vulnerability, check it in dependency check
Done with build ran and test it locally
> mitgate micro-profile vulnerablity

- a2d2-api/pom.xml
Tested by building and running a2d2 on local. also run Omnibus and executed API
> mitigated spring-core vulnearbility

- a2d2-api/pom.xml
Done with mitigate tomcat embed core 9.0.48 vulnerability,
Done with build, ran and test a2d2 and omnibus locally
>  mitigate tomcat embed core 9.0.48 vulnerability

- a2d2-api/pom.xml
Done with mitigate resteasy client  vulnerability,
Done with build, ran and test a2d2 and omnibus locally
> mitigate resteasy client vulnerability

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
@ddjain and @vdeshkar this might confilict with some of your PRs but it solves all the dependency vulnerabilities except three low ones
> Gt 593 multiple dependencies check

- a2d2-api/pom.xml
- kie-based-services/pom.xml
- pom.xml
- service-daos/pom.xml
Updates log4j version to 2.17.0 to address vulnerabilities
> GT-596 log4j version updates

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- kie-based-services/pom.xml
- pom.xml
- service-daos/pom.xml
Done with mitigate tomcat-embed-core by updating spring boot version
Done with build and ran uni test case on local successfully
> Upgrade spring boot version to mitigate tomcat-embed-core in a2d2

- fhir-query-helper-base/pom.xml
- pom.xml
Mitigated netty transport vulnerability.
> Mitigate netty transport

- pom.xml
Tested by running jedis client against Redis 6.0
> updated jedis dependency to latest version

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- kie-based-services/pom.xml
- pom.xml
As suggested by @marianbuenosayres , to keep consistency updated **kie.version** throughout project also creating PR in omnibus.
Tested locally by building and running Unit test cases.
> Fixed vulnerability for jackson databind

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- kie-based-services/pom.xml
- pom.xml
Reverts elimuinformatics/a2d2#105
> Revert "Fixed vulnerability for jackson databind"

- a2d2-api/pom.xml
- pom.xml
- task-utilities/pom.xml
Resolves some of the build warnings and updates a few plugins, but the deprecation warnings still need to be resolved. Also fixed the cases of mixed tabs/spaces I found.
Tested by running unit tests.
> Resolves some of the build warnings

- a2d2-api/src/main/java/io/elimu/cdshookapi/api/config/CDSHookConfig.java
- a2d2-api/src/main/java/io/elimu/utils/CorrelationInterceptor.java
- a2d2-api/src/test/java/io/elimu/a2d2/processtest/GenericTestUtils.java
- cds-hook-services/src/main/java/io/elimu/cdshookapi/service/TaskServiceHelper.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/cache/CacheUtil.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/cache/InMemoryCache.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/cache/JedisCache.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelperBase.java
- fhir-query-helper-dstu2/src/test/java/io/elimu/a2d2/cds/fhir/cache/test/JedisTest.java
- fhir-query-helper-dstu2/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperTest.java
- fhir-query-helper-dstu3/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperTest.java
- kie-based-services/src/main/java/io/elimu/genericapi/scrubbers/HtmlInputScrubber.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericKieBasedService.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/InternalUpdateTaskCommand.java
- kie-based-services/src/test/java/io/elimu/genericapi/service/InputScrubbersTest.java
- kie-based-services/src/test/java/io/elimu/genericapi/service/MavenJarResolverTest.java
- kie-based-services/src/test/java/io/elimu/genericapi/service/RunningServicesTest.java
- service-daos/src/main/java/io/elimu/service/dao/jpa/ServiceRulesRepository.java
- sms-wih/src/main/java/io/elimu/a2d2/smswih/PhoneValidationWorkItemHandler.java
- task-utilities/src/test/java/io/elimu/task/fhir/r4/R4FhirTaskTest.java
Tested locally and validated everything still works
> Corrections to warnings in compilation

- kie-based-services/src/main/java/io/elimu/genericapi/plugins/ModulePluginLoader.java
> Fix for build warning in ModulePluginLoader

- a2d2-api/pom.xml
- a2d2-api/src/main/java/io/elimu/cdshookapi/api/rest/SimpleServiceController.java
- cds-hook-services/pom.xml
- pom.xml
- service-daos/pom.xml
Done with update the spring version 5.3.15, Update spring version and also update the spring boot starter parent to version 2.6.2, Some spring dependencies with version 5.3.14 are coming from spring boot starter parent version 2.6.2.
Done with build, ran and ran it on local
> Update spring version to 5.3.15

- a2d2-api/pom.xml
- cds-hook-model/pom.xml
- cds-hook-services/pom.xml
- core-dependencies/datafetch-service/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- core-dependencies/pom.xml
- fhir-helpers/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-r4/pom.xml
- generic-helpers/pom.xml
- generic-model/pom.xml
- kie-based-services/pom.xml
- service-daos/pom.xml
- task-utilities/pom.xml
Tested by building and running unit tests locally. There are no real code changes or dependency changes, so this should be very low risk.
> Fixes some build and site reporting warnings

- a2d2-api/pom.xml
Done with mitigate tomcat embed core, update version 9.0.56 to 9.0.62
Done with build and install and ran all integration test case
> mitigate tomcat embed core dependency

- cds-hook-model/src/main/java/io/elimu/a2d2/serviceapi/performance/PerformanceHelper.java
- core-wih/src/main/java/io/elimu/a2d2/corewih/MixPanelWorkItemHandler.java
- generic-helpers/src/main/java/io/elimu/a2d2/helpers/MixPanelService.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/MixPanelEventListener.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/MixPanelStack.java
- kie-based-services/src/test/java/io/elimu/genericapi/service/MixPanelTest.java
Contains the changes necessary to manage HTTP header request distinct id and mixpanel fields.
> Gt 672 added distinct id management

- core-dependencies/fhir-parse-util/src/test/java/io/elimu/a2d2/parsing/FhirParseUtilTest.java
- core-wih/src/main/java/io/elimu/a2d2/corewih/MixPanelWorkItemHandler.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericKieBasedService.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/MixPanelEventListener.java
- kie-based-services/src/main/java/io/elimu/serviceapi/config/CachedResult.java
- kie-based-services/src/main/java/io/elimu/serviceapi/config/ConfigAPIProcessVariableInitHelper.java
- kie-based-services/src/main/java/io/elimu/serviceapi/config/ConfigAPIUtil.java
- kie-based-services/src/main/java/io/elimu/serviceapi/config/ConfigAPIWorkItemHandler.java
- kie-based-services/src/test/java/io/elimu/serviceapi/config/ConfigAPIUtilTest.java
Provides config-api process variable initialization, as well as a work item handler for managing updates for long running processes.
> Gt 668 config api work

- kie-based-services/src/main/java/io/elimu/genericapi/service/MixPanelEventListener.java
Fixes a missing eventDescription in one of the events
> Fix to EventListener missing one property

- service-daos/pom.xml
Mitigated spring-orm vulnerablity
> Mitigated spring-orm-vulnerability

- core-dependencies/datafetch-service/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- fhir-helpers/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-r4/pom.xml
- fhir-resource-wih/pom.xml
- ftl-transform-wih/pom.xml
- kie-based-services/pom.xml
- oauth-helpers/pom.xml
- pom.xml
Mitigated okhttp vulnerability
> mitigated okhttp vulnerability

- a2d2-api/pom.xml
- cds-hook-model/pom.xml
- cds-hook-services/pom.xml
- cdshooks-wih/pom.xml
- core-dependencies/datafetch-service/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- core-dependencies/pom.xml
- core-wih/pom.xml
- fhir-helpers/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-r4/pom.xml
- fhir-resource-wih/pom.xml
- ftl-transform-wih/pom.xml
- generic-helpers/pom.xml
- generic-model/pom.xml
- kie-based-services/pom.xml
- oauth-helpers/pom.xml
- pom.xml
- service-daos/pom.xml
- service-daos/src/main/java/io/elimu/service/models/ServiceInfo.java
- sms-wih/pom.xml
- web-util/pom.xml
Plus removal of unnecessary import
> GT-779 added null-checks for ServiceInfo initialization

- core-wih/pom.xml
- fhir-resource-wih/pom.xml
- pom.xml
Done with mitigate gson vulnerability,
Done with test it on local
> Done with mitigate-gson-vulnerability

- a2d2-api/pom.xml
- cds-hook-model/pom.xml
- cds-hook-services/pom.xml
- cdshooks-wih/pom.xml
- core-dependencies/datafetch-service/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- core-dependencies/pom.xml
- core-wih/pom.xml
- fhir-helpers/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-r4/pom.xml
- fhir-resource-wih/pom.xml
- ftl-transform-wih/pom.xml
- generic-helpers/pom.xml
- generic-model/pom.xml
- kie-based-services/pom.xml
- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericKieBasedService.java
- oauth-helpers/pom.xml
- pom.xml
- service-daos/pom.xml
- sms-wih/pom.xml
- web-util/pom.xml
Added possiblity of using * as space, which would translate at config request time into "default" for fetching configuration
> GT-779 adding handling of '*' space configuration

- a2d2-api/pom.xml
Mitigated vulnerability okhttp of high severity.
> mitigated okhhtp vulnerability updated POM

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- core-wih/pom.xml
- pom.xml
- service-daos/pom.xml
Reverts elimuinformatics/a2d2#152
> Revert "Bump spring-core from 5.3.19 to 5.3.20 in /a2d2-api"

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- pom.xml
- service-daos/pom.xml
Updating spring boot starter version to `2.7.1`, Its mitigating some of more vulnernability from report and mitigating spring-core:`5.3.19`, Update the same version in the omnibus creating PR and merge both with same.
Done with test by running integration test cases of stage and qa on local.
> updating spring boot version

- a2d2-api/pom.xml
- fhir-helpers/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryBuilder.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelperBase.java
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu2/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelper.java
- fhir-query-helper-dstu2/src/test/java/io/elimu/a2d2/cds/fhir/cache/test/QueryingServerHelperCacheTest.java
- fhir-query-helper-dstu2/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperTest.java
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-dstu3/src/main/java/io/elimu/a2d2/cds/fhir/helper/dstu3/QueryingServerHelper.java
- fhir-query-helper-dstu3/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperCacheTest.java
- fhir-query-helper-r4/pom.xml
- fhir-query-helper-r4/src/main/java/io/elimu/a2d2/cds/fhir/helper/r4/QueryingServerHelper.java
- fhir-query-helper-r4/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/FhirTest.java
- fhir-query-helper-r4/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperCacheTest.java
- generic-helpers/pom.xml
- oauth-helpers/pom.xml
- oauth-helpers/src/test/java/io/elimu/a2d2/OAuthHelperTest.java
- pom.xml
Creates a QueryBuilder to add the different functionalities on a single object and method. Keeping the Async apart because of the different return type
> Added QueryBuilder functionality for QueryingServerHelper

- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/TimeObject.java
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
There was an issue with the fetch of PlanDefinition using planDefinitionUrl input. This PR fixes it and adds a test for it. Also, more debug logging was added
> CQL updates to use more logging and filter by URL correctly

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- core-wih/pom.xml
- pom.xml
- service-daos/pom.xml
Reverts elimuinformatics/a2d2#175
> Revert "Mitigate Spring related dependency"

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- core-wih/pom.xml
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
- pom.xml
- service-daos/pom.xml
Reverts elimuinformatics/a2d2#179
> "Mitigate Spring related dependency"

- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
> Cql changes removal of test in dev

- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
> CQL changes added to master

- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
Added corrections to reflection code
> Cql corrections

- pom.xml
Reverts elimuinformatics/a2d2#192
Reverting PR because test cases are failing
> Revert "Mitigate jbpm-bpmn2 Vulnerability"

- a2d2-api/pom.xml
When I generate a report I spring security core vulnerable, found it vulnerable, Once mitigate it found another one and conflict while build, exclude all of same version and include all with latest version and build and ran with integration test case, make changes in omnibus as well and start testing it,
Done with ran it with omnibus and ran all the integration test cases
> Miitgate spring security vulnerability

- owasp-dependency-check-suppressions.xml
> Suppressed the vulnerability xstream

- owasp-dependency-check-suppressions.xml
> Supressed the POI vulnerability 

- core-wih/src/main/java/io/elimu/a2d2/corewih/OAuth2WorkItemHandler.java
Updated the scope for a2d2, changes it from offline_access to use openid
> Updates scope for OAuth

- README.md
- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- core-dependencies/datafetch-service/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- fhir-helpers/pom.xml
- fhir-query-helper-dstu2/pom.xml
- kie-based-services/pom.xml
- pom.xml
- service-daos/pom.xml
- task-utilities/pom.xml
Update the version from 1.8 to 11,
point with omnibus and ran omnibus on local and ran the integration test cases of stage env.
> Update jdk version from 1.8 to 11

- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
Adds context param handling and different types of parameters other than resource
> CQL context params handling for different types of parameter passing

- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
Added list handling for CQL contexts and prefetches
> Cql context params handling

- pom.xml
mitigating vulnerability sshd-common
> Mitigates vulnerability sshd-common

- kie-based-services/src/main/java/io/elimu/serviceapi/config/JWTAuthUtil.java
Adds support for another algorithm
> ES384 support for JWT authentication

- kie-based-services/src/main/java/io/elimu/serviceapi/config/JWTAuthUtil.java
- kie-based-services/src/main/java/io/elimu/serviceapi/config/SimpleECDSAKeyProvider.java
> Jwt es384 support

- pom.xml
mitigated netty transport vulnerability
- Tested by running omnibus on local 
- Also ran sofa-omnibus-service-integration-test-stage on local
-
> mitigate netty transport vulnerability

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- pom.xml
- service-daos/pom.xml
Upgraded version of spring boot to latest stable that supports java -11
> upgraded springboot version

- cds-hook-services/src/main/java/io/elimu/cdshookapi/service/ServiceHelper.java
Modifies the initialization to match hot deploy behavior in an attempt to start services with dependency problems
> Updated initialization to match hot deploy behavior as well

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- ftl-transform-wih/pom.xml
- kie-based-services/pom.xml
mitigated tomcat-embed-core vulnerability
> mitigated vulnerability tomcat-embed-core

- a2d2-api/pom.xml
mitigated tomcat-embed-websocket vulnerability
> mitigated vulnerability tomcat-embed-websocket

- a2d2-api/pom.xml
- kie-based-services/pom.xml
- pom.xml
- service-daos/pom.xml
- Ran application successfully  on local .
> removed exclusion from a2d2 for log4j-to-slf4j to use latest vesrion

- kie-based-services/pom.xml
ran project on local successfully.
> removed exclusion classmate from  a2d2

- kie-based-services/pom.xml
Remove apiguardian-api exclusion from spring-boot in a2d2
> remove apiguardian exclusion

- cds-hook-services/pom.xml
- kie-based-services/pom.xml
- pom.xml
- sms-wih/pom.xml
Ran project on local verify working fine.
> removes extra exlusions for jackson annotations

- cds-hook-model/pom.xml
- cds-hook-services/pom.xml
- fhir-query-helper-base/pom.xml
- kie-based-services/pom.xml
- sms-wih/pom.xml
- task-utilities/pom.xml
Remove jackson core exclusion from spring-boot in a2d2
> remove jackson core exclusion

- cds-hook-model/pom.xml
- cds-hook-services/pom.xml
- cql-wih/pom.xml
- kie-based-services/pom.xml
- pom.xml
- task-utilities/pom.xml
ran project on local successfully.
> Remove exclusions jackson databind

- a2d2-api/pom.xml
- cds-integration/pom.xml
- ftl-transform-wih/pom.xml
- kie-based-services/pom.xml
- service-daos/pom.xml
Ran project on local and verifies working correctly.
> removes extra exclusions of spring

- cds-hook-model/pom.xml
- core-dependencies/datafetch-service/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-resource-wih/pom.xml
- ftl-transform-wih/pom.xml
- kie-based-services/pom.xml
- pom.xml
Remove slf4j-api exclusion from spring-boot in a2d2
> remove slf4j-api exclusion

- kie-based-services/pom.xml
- pom.xml
Ran project on local successfully.
> removes exclusion jboss

- kie-based-services/pom.xml
- pom.xml
Remove junit-platform-commons exclusion from spring-boot in a2d2
> exclusion junit platform commons

- kie-based-services/src/main/java/io/elimu/serviceapi/config/JWTAuthUtil.java
Handle provided key "jwtValidPrestKeys" with base64 encoded X509 certificates, instead of trying to resolve them from JKU as only option.
> Handle provided public keys in JWT utility

- core-wih/pom.xml
- cql-wih/pom.xml
- fhir-query-helper-base/pom.xml
- kie-based-services/pom.xml
- pom.xml
> mitigated json

- kie-based-services/src/main/java/io/elimu/serviceapi/config/JWTAuthUtil.java
This provides the possiblity of handling multiple preset keys, with the caveat that the positions in the array must match the positions of the jwtValidIss property. For the iss values that are not with preset keys, the text "invalid" must be placed in its corresponding position in the jwtValidPresetKeys property.
> jwt auth provided secrets as comma separated list

- kie-based-services/src/main/java/io/elimu/serviceapi/config/JWTAuthUtil.java
Log entries for JWT token parsing functionality, plus error logging with stacktrace
> Gt 1099 jwt auth provided secrets

- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
WorkItemHandler parameters with name starting in fhirServer_header_Header__Value will be added with key "Header-Value" to the data endpoint
WorkItemHandler parameters with name starting in fhirTerminologyServer_header_Header__Value will be added with key "Header-Value" to the terminology endpoint
> Cql Executor custom headers addition now possible

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
- owasp-dependency-check-suppressions.xml
Mitigated resteasy-core vulnerability
> Mitigated vulnerability resteasy-core

- Dockerfile
- README.md
- Built docker without environments
- Tested by run docker on local
> building docker without nexus username & password

- owasp-dependency-check-suppressions.xml
Mitigated wildfly elytron vulnerability
> mitigate vulnerability wildfly-elytron

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- ftl-transform-wih/pom.xml
- kie-based-services/pom.xml
- task-utilities/pom.xml
Mitigated plexus utils vulnerability
> Mitigate vulnerability plexus utils

- owasp-dependency-check-suppressions.xml
Added suppression for plexus-utils-3.5.1.jar
> Mitigated vulnerability plexus utils

- owasp-dependency-check-suppressions.xml
- Added suppression for json-20220924.jar because it is false positive
> Mitigate dependency json-20220924.jar by adding suppression

- cds-hook-model/src/main/java/io/elimu/a2d2/cdsresponse/entity/Card.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/CardCreator.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
This allows us to populate the overrideReasons from the output of a PlanDefinitionProcessor
> CQL overrideReasons population

- cds-hook-model/src/main/java/io/elimu/a2d2/cdsresponse/entity/Card.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/CardCreator.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
Work to output cql evaluations as part of the results of the work item
> Cql override reasons population

- kie-based-services/pom.xml
- owasp-dependency-check-suppressions.xml
Reverted old changes & Added exclusion because it not using a2d2.
> Reverted old changes & Added exclusion for cxf-rt-binding-soap changes

- .github/workflows/docker-image.yml
Its uses to publish a Docker image on public docker hub account
> docker-image.yml for publishing the docker image on docker hub using git hub actions

- owasp-dependency-check-suppressions.xml
> suppressed org.hl7.fhir.utilities vulnerability

- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
We take the output of evaluating the ActivityDefinition, and if possible to set an Intent from the value of the ActivityDefinition, we set it for the output object.
> CQL ActivityDefinition's intent is now passed to the result object if possible

- cds-hook-services/pom.xml
- fhir-resource-wih/pom.xml
Mitigated json-smart-2.4.8 vulnerability
- Tested application by running on local
> Mitigate vulnerability json-smart-2.4.8

- .github/workflows/docker-image.yml
- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericKieBasedService.java
- kie-based-services/src/main/java/io/elimu/serviceapi/config/ConfigAPIProcessVariableInitHelper.java
- kie-based-services/src/main/java/io/elimu/serviceapi/config/ConfigAPIUtil.java
- kie-based-services/src/main/java/io/elimu/serviceapi/config/ConfigAPIWorkItemHandler.java
- Added Timeout exception & error message
> Manage omnibus config api timeout error

- cql-wih/src/main/java/io/elimu/a2d2/cql/CardCreator.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
Allows the ActivityDefintion.description to be the part populating the output Card suggestions
> CQL ActivityDefinition.description populating the suggestions

- a2d2-api/pom.xml
Mitigated tomcat-embed-core-9.0.71.jar vulnerability
- Tested application by running on local
> Mitigate vulnerability tomcat-embed-core-9.0.71.jar

- .github/workflows/docker-image.yml
- a2d2-api/pom.xml
Mitigated resteasy-client-4.7.2.Final.jar vulnerability
- Tested application by running on local
> Mitigate vulnerability resteasy-client-4.7.2.Final.jar

- cql-wih/src/main/java/io/elimu/a2d2/cql/CardCreator.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
makes sure we populate the suggestions type if possible
> GT-1207 fixes for suggestion type population

- cql-wih/src/main/java/io/elimu/a2d2/cql/CardCreator.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
Covers requested card suggestion unificaiton, as well as missing properties for suggestions
> Gt 1207 action types

- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
I managed to reproduce and create a potential fix for an issue parsing the CQL parsing/execution. Will review with @boxwala in a meeting on monday
> CQL Issues initial test case and fixes

- core-dependencies/fhir-parse-util/src/main/java/io/elimu/a2d2/parsing/FhirParseUtil.java
Makes sure the tabulated outcome is not the selected option before creating the JSON/XML output
> RAD-487 compressed output

- a2d2-api/src/main/java/io/elimu/cdshookapi/api/config/CDSHookConfig.java
- a2d2-api/src/main/resources/META-INF/persistence.xml
- a2d2-api/src/main/resources/application.yml
- cds-hook-services/src/test/resources/META-INF/persistence.xml
Added the environment variable, which we have use to set the value for hibernate show sql,
We will set the env it in task definition by default value false, and update the value to true when we want to check the logging 
Removed hibernate logging
- Tested by running on local
> Removing hibernate logging

- README.md
- generic-helpers/pom.xml
- generic-helpers/src/main/java/io/elimu/a2d2/helpers/JedisHelper.java
- generic-helpers/src/test/java/io/elimu/a2d2/helpers/JedisHelperTest.java
Allows to manage shared caches between nodes for quick value recovers
> JedisHelper addition

- cds-hook-model/src/main/java/io/elimu/a2d2/cdsresponse/entity/Suggestion.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/CardCreator.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
Added code to parse precheckBehavior into isRecommended values for cds card suggestions
> CQL isRecommended for suggestions added

- .github/workflows/docker-image.yml
- Docker-README.md
- Adding a steps to fetch the readme.md and update it as description of docker image on docker hub,
> When I pull the a2d2 docker image from docker hub, I have a readme file in documentation, so that I know how to configure and run it

- .github/workflows/docker-image.yml
- Dockerhub-README.md
- Added dockerhub-readme.md file and point this in github workflow file,
So, whenever git actions executes it will update the description,
> Updated docker readme file

- fhir-query-helper-base/pom.xml
Mitigate dependency vulnerability in a2d2: redisson-3.18.0.jar
> Mitigate dependency vulnerability in a2d2: redisson-3.18.0.jar

- a2d2-api/pom.xml
- a2d2-settings.xml
- deploy.sh
- fhir-helpers/pom.xml
- pom.xml
- task-utilities/pom.xml
- Added AWS CodeArtifact configuration in a2d2-settings.xml & pom.xml.
- Tested by building a2d2 on local.
> Integrate code artifact with a2d2

- a2d2-settings.xml
- pom.xml
Adding maven central as option in parent pom.xml and settings.xml
> Integrating code artifact suggestions

- a2d2-api/pom.xml
- fhir-helpers/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/FetchCallRetry.java
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-r4/pom.xml
- generic-helpers/pom.xml
- oauth-helpers/pom.xml
- pom.xml
The http body response from fhir server has been added in an error log.
> Rad 994 add http body response
