- a2d2-api/src/test/java/io/elimu/a2d2/processtest/GenericServiceTest.java
- a2d2-api/src/test/java/io/elimu/a2d2/processtest/GenericTestUtils.java
- a2d2-api/src/test/resources/generic-example-db-service.dsl
- a2d2-api/src/test/resources/generic-example-service.dsl
GenericServiceIntegrationTest depends in escence on an external maven repository. So will remain Ignored and possibly even deleted. 
GenericServiceTest has been updated to work offline with a mock environment. Updated tests to ignore the authtype/validationtype components until decision on how to implement
> BT-91 added updates to GenericServiceTest

- cdshooks-wih/pom.xml
Putting kie-based-services as a test dependency is not correct, because it is an internal component in the runtime that the WIH does not depend on directly. Instead, we need to add org.kie:kie-api as a dependency for the WorkItemHandler class dependency, and drools-core/kie-dmn-core as test dependencies for the test requirements
> BT-108 updated dependencies on cdshooks-wih to the right ones

- fhir-helpers/pom.xml
- fhir-helpers/src/main/java/io/elimu/a2d2/fhir/FhirTransformHelper.java
- fhir-helpers/src/test/java/io/elimu/a2d2/fhir/FhirTransformHelperTest.java
- fhir-helpers/src/test/resources/allergy-intolerance.json
- fhir-helpers/src/test/resources/condition.json
- fhir-helpers/src/test/resources/medication-order.json
- fhir-helpers/src/test/resources/patient.json
- fhir-helpers/src/test/resources/questionnaire-response.json
- pom.xml
this helper allows us to transform DSTU2 and DSTU3 fhir domain objects into R4 objects. Due to the limitations of the provided converters, this is a workaround for that problem.
> Helper to transform DSTU2/3 to R4

- fhir-helpers/pom.xml
- fhir-helpers/src/main/java/io/elimu/a2d2/fhir/FhirTransformHelper.java
- fhir-helpers/src/test/java/io/elimu/a2d2/fhir/FhirTransformHelperTest.java
- fhir-helpers/src/test/resources/procedure-1.json
- fhir-helpers/src/test/resources/procedure-2.json
- fhir-query-helper-base/pom.xml
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/cache/CacheUtil.java
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-r4/pom.xml
- pom.xml
This is because some servers will reply with an HTTP 400 if we send Bearer tokens using SimpleHeaderInterceptor classes. For those cases we need to use BearerTokenAuthInterceptor through method addAuthentication("Bearer", token). These changes are to make sure the Cache mechanisms do not fail to interpretate such interceptors when they are added
> Cache keys for multi interceptor types

- a2d2-api/pom.xml
Because the hapi-fhir-base JAR is at webapp level in the classloader, and it uses reflection in the same classloader as it is to transform from one model to the other, we need to add the hapi-fhir-converter and hapi-fhir-structures-hl7org-dstu2 JARs to the app in order for applications to use the FHIR converter without ClassCastExceptions
> Adding dependencies needed for FHIR conveters

- Dockerfile
Declared default ports and removed the health check URL which is on 8080, as we are specifying the port and health check on runtime.
> Updated Dockerfile for ports

- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/ResourceWriteDelegate.java
In some services, "authHeader" input is left as null if the FHIR server used has no authorization required (in some internal installations it has been the case). This makes sure that if the param is missing, it will not throw a NullPointerException
> Null-checking the authHeader, which some services might leave null

- a2d2-api/src/main/java/io/elimu/cdshookapi/api/rest/StatusController.java
- cds-hook-model/src/main/java/io/elimu/a2d2/oauth/OAuthUtils.java
- fhir-query-helper-base/pom.xml
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelperBase.java
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu2/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelper.java
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-dstu3/src/main/java/io/elimu/a2d2/cds/fhir/helper/dstu3/QueryingServerHelper.java
- fhir-query-helper-r4/pom.xml
- fhir-query-helper-r4/src/main/java/io/elimu/a2d2/cds/fhir/helper/r4/QueryingServerHelper.java
- fhir-query-helper-r4/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/FhirTest.java
- kie-based-services/pom.xml
- kie-based-services/src/main/java/io/elimu/genericapi/plugins/PKeyLoaderPluginLoader.java
- pom.xml
Allows us to build a JWT token, do direct path fetches for FHIR queries, and adds a new status controller to replace the actuator reference to something related to our internal status
> FHIR query helpers, status controller, and OAuth utilities update

- kie-based-services/src/main/java/io/elimu/genericapi/service/RunningServices.java
Added option to restartService without storing. Used for hot deploy features to not continuously redeploy when a hot deploy is done
> new restartService method

- kie-based-services/src/main/java/io/elimu/serviceapi/service/ProcessVariableInitHelper.java
- kie-based-services/src/test/java/io/elimu/serviceapi/service/ProcessVariableInitHelperTest.java
We already had the chance of doing this with JVM properties:
-Dproc.envvar.prefix=a2d2 -Da2d2.service-1.variable-a=123 -Da2d2.service-2.variable-a=123 -Da2d2.service-3.variable-a=123
The purpose of this pull request is to be able to have JVM variables like this:
-Dproc.envvar.prefix=a2d2 -Da2d2.**allservices**.variable-a=123
That would work for all services (service-1, service-2, etc)
If in the future we need to have a different value for one specific service, this is also possible:
-Dproc.envvar.prefix=a2d2 -Da2d2.allservices.variable-a=123 -Da2d2.special-service.variable-a=456
Where all services will have variable-a preinitialized with 123, except special-service, which will use 456
> Added initializer so that we can use default, cross-service variables

- kie-based-services/src/main/java/io/elimu/genericapi/service/MavenJarResolver.java
- kie-based-services/src/main/java/io/elimu/serviceapi/service/AbstractKieService.java
- pom.xml
These changes are required to make sure already registered RuntimeManagers, upon recreation, are reconstructed from the ground up with the new dependencies.
> Hot deploy component updates

- oauth-helpers/pom.xml
- oauth-helpers/src/main/java/io/elimu/a2d2/NDOFilter.java
- oauth-helpers/src/main/java/io/elimu/a2d2/OAuthHelper.java
- oauth-helpers/src/test/java/io/elimu/a2d2/OAuthHelperTest.java
- pom.xml
The purpose of this PR is to create an even simpler OAuth helper, that just will search the variables for you. In this helper, assuming you have predefined variables for OAuth token obtaining, you can simply do this call in the rules:
`import io.elimu.a2d2.cds.fhir.helper.r4.QueryingServerHelper;
import io.elimu.a2d2.genericmodel.NamedDataObject;
import io.elimu.a2d2.OAuthHelper;
rule "test" 
salience 10
when
qsh: QueryingServerHelper()
NamedDataObject(name == "fhirScope")
then
OAuthHelper.addOAuthToken(drools, qsh);
end`
Similarly, you could do this:
`import io.elimu.a2d2.cds.fhir.helper.r4.QueryingServerHelper;
import io.elimu.a2d2.genericmodel.NamedDataObject;
import io.elimu.a2d2.OAuthHelper;
rule "test" 
salience 10
when
qsh: QueryingServerHelper()
NamedDataObject(name == …
> OAuthHelper for simpler OAuth management

- README.md
- cds-hook-services/src/main/java/io/elimu/cdshookapi/service/ServiceHelper.java
- core-wih/src/main/java/io/elimu/a2d2/rulewih/RuleInvokeDelegate.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericDebugListener.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericKieBasedService.java
- service-daos/src/main/java/io/elimu/service/dao/jpa/CDSServiceRepository.java
Given the following HTTP headers, you will see debug info from listeners:
1) HTTP Header X-Enable-Debug with value true: The server logs will contain information of listeners for the different rule and process evnets
2) HTTP Header X-Output-Debug with value true: The body of the HTTP response will be a JSON, with one attribute being the initial response, and another one being the events list as JSON output. 
Special attention was added so that the output stored was not exposing variables with the name "password" in them in the HTTP response
> logger for outputting rule and process exeutions in the response

- fhir-resource-wih/pom.xml
- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/OperationOutcomeDelegate.java
- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/OperationOutcomeWorkItemHandler.java
- fhir-resource-wih/src/test/java/io/elimu/a2d2/fhir_resource_wih/OpOutcomeWIHTest.java
This OperaitonOutcomeWorkItemHandler will generate three things:
- An OperationOutcome FHIR object
- A JSON containing variable
- A ServiceResponse object prepared to return an OperationOutcome
The expected inputs are:
- fhirVersion: optional, by default it will use R4. Will expect values FHIR2, FHIR3, FHIR4, DSTU2, DSTU3, R4
- response_status: an Integer with the HTTP status to return (if a ServiceResponse is the output expected)
And a set of variable inputs starting with issue_, any identifier ending in _, and a set of key names for allowing different issue elements, like this:
- issue_a_code: The issue type
- issue_a_details: The details CodeableConcept’s text attribute
- issue_a_detailsCode: The details CodeableConcept’s code attribute
- issue_a_detailsSystem: The details …
> OperationOutcomeWorkItemHandler 

- pom.xml
Running "mvn site" with version 5.3.2 generates the following error :
"[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7.1:site (default-site) on project parent: Error generating dependency-check-maven:5.3.2:aggregate report: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during analysis:
[ERROR] Unable to resolve system scoped dependency: com.sun:tools:jar:1.8.0:system"
Updating to 6.2.2 resolves that.
> Updated version of dependency-check-maven to 6.2.2

- generic-helpers/pom.xml
- generic-helpers/src/main/java/io/elimu/a2d2/helpers/SingletonHolder.java
This is to enable some stateful functionality regarding pool creations and stuff like that which needs to be done only once on a service
> Generic singleton holder for stateful service helping

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- cds-integration/pom.xml
- fhir-helpers/pom.xml
- kie-based-services/pom.xml
- pom.xml
- service-daos/pom.xml
- task-utilities/pom.xml
Springboot 2.2.9 was released a year ago. This change brings Springboot to 2.4.8 which does many bug fixes and dependency upgrades(https://github.com/spring-projects/spring-boot/releases/tag/v2.4.8).
I've run unit tests locally.
> Updated A2D2 Springboot to 2.4.8 and resolved dependencies.

- fhir-helpers/pom.xml
Resolved the following error:
"Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed: A required class was missing while executing org.apache.maven.plugins:maven-site-plugin:3.3:site: org/apache/maven/doxia/siterenderer/DocumentContent"
I've run tests locally.
> Added maven-site plug in to fhir-helpers

- a2d2-api/pom.xml
Resolved the following error:
"Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed: A required class was missing while executing org.apache.maven.plugins:maven-site-plugin:3.3:site: org/apache/maven/doxia/siterenderer/DocumentContent"
I've run tests locally.
> Added maven-site plug in to a2d2-api

- a2d2-api/pom.xml
Vulnerability IDs:
cpe:2.3:a:bouncycastle:legion-of-the-bouncy-castle:1.51:*:*:*:*:*:*:*
cpe:2.3:a:bouncycastle:legion-of-the-bouncy-castle-java-crytography-api:1.51:*:*:*:*:*:*:*
Resolved by upgrading to version 1.61.
I've run tests locally.
> Mitigated dependency vulnerabilities caused by bcprov-jdk15on-1.51.jar, updated versions

- a2d2-api/pom.xml
- kie-based-services/pom.xml
- pom.xml
1. resteasy-core-4.5.2.Final.jar
Vulnerability IDs:
cpe:2.3:a:redhat:resteasy:4.5.2:*:*:*:*:*:*:*
Resolved by upgrading to version 4.6.0.
2. json-sanitizer-1.2.0.jar
Vulnerability IDs:  
cpe:2.3:a:owasp:json-sanitizer:1.2.0:*:*:*:*:*:*:*
Resolved by upgrading to version 1.2.2.
3. jackson-databind-2.9.10.5.jar
Vulnerability IDs:  
cpe:2.3:a:fasterxml:jackson-databind:2.9.10.5:*:*:*:*:*:*:*
cpe:2.3:a:fasterxml:jackson-modules-java8:2.9.10.5:*:*:*:*:*:*:*
Resolved by upgrading to version 2.9.10.8.
I've run tests locally
> Mitigate dependency vulnerabilities caused by resteasy-core-4.5.2.Final.jar, json-sanitizer-1.2.0.jar and jackson-databind-2.9.10.5.jar

- core-wih/pom.xml
- kie-based-services/pom.xml
1. spring-core-5.2.6.RELEASE.jar
Vulnerability IDs:
cpe:2.3:a:pivotal_software:spring_framework:5.2.6:release:*:*:*:*:*:*
cpe:2.3:a:springsource:spring_framework:5.2.6:release:*:*:*:*:*:*
cpe:2.3:a:vmware:spring_framework:5.2.6:release:*:*:*:*:*:*
cpe:2.3:a:vmware:springsource_spring_framework:5.2.6:release:*:*:*:*:*:*
Resolved by upgrading to version 5.3.8
2. cxf-core-3.2.14.jar
Vulnerability IDs:
cpe:2.3:a:apache:cxf:3.2.14:*:*:*:*:*:*:*
Resolved by upgrading to version 3.3.11
I've run tests locally.
> Mitigated dependency vulnerabilities caused by spring-core-5.2.6.RELEASE.jar and cxf-core-3.2.14.jar

- ftl-transform-wih/pom.xml
build warning message:
[WARNING] Some problems were encountered while building the effective model for io.elimu.a2d2:ftl-transform-wih:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.elimu.a2d2:cds-hook-model:jar -> duplicate declaration of version (?) @ line 132, column 15
[WARNING]
solution: remove duplicate entry
> Removed duplicate entry in ftl-transform-wih/pom.xml

- Dockerfile
adoptopenjdk/openjdk11:jdk-11.0.6_10-alpine-slim image size 253 MB with a2d2 image size 440MB.
> GT-469:Need a smaller docker base image for a2d2

- Dockerfile
Starting on April 20, 2021, quarterly update releases of OpenJDK are disabling TLS1.0 and TLS1.1 availability by default. This could cause SSL connection problems. Switch to an older image.
I have tested locally
> Use openjdk11:jre-11.0.10_9-alpine as a2d2 docker base image

- a2d2-api/pom.xml
- kie-based-services/pom.xml
Resolved high and critical vulnerabilty in omnibus
> Mitigated dependency vulnerabilities caused by com.thoughtworks.xstream.xstream.1.4.17 and org.jsoup.jsoup.1.12.1

- sms-wih/src/main/java/io/elimu/a2d2/smswih/PhoneValidationWorkItemHandler.java
- sms-wih/src/test/java/io/elimu/a2d2/smswih/ValidationTest.java
This will add to the SMS phone Validation WIH that it also checks the given phone is not a "landline" which wouldn't be able to receive SMS messages
> GT-557 updated so it filters out 'landlines' as well

- a2d2-api/pom.xml
Mitigated vulnerability for `resteasy-core-4.6.0` with `4.7.3.Final`.
Tested by building A2D2 app. and also run omnibus api and executed service.
> GT-471 Mitigated vulnerability for resteasy-core-4.6.0

- a2d2-api/pom.xml
- pom.xml
Done with mitigate log4j-api vulnerability to 2.17.1.
Done with build and run test cases on local
> Mitigate log4j api 2.17.0 vulnerability to 2.17.1

- a2d2-api/pom.xml
Done with update the logback-core version 1.2.3 to 1.2.9 to mitigate the vulnerability
Done with build and ran unit test on local
> Mitigate logback core vulnerability to v-1.2.9

- task-utilities/pom.xml
old version of **jackson-databind@2.10.4** was comming thorugh org.jbpm:jbpm-human-task-core
updating kie version mitigated vulnerability for jackson-databind.
Tested locally by running unit test case and executed API.
> Fixed vulnerability for jackson databind by updating kie version

- a2d2-api/pom.xml
- cdshooks-wih/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- core-wih/pom.xml
- fhir-resource-wih/pom.xml
- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/FHIRDelegateHelper.java
- ftl-transform-wih/pom.xml
- kie-based-services/pom.xml
- sms-wih/pom.xml
We were having a problem with our services because our Jenkins server was not able to get the right version of dependencies deployed. They were instead getting old snapshots. In order to prevent this, we created a new snapshot version 0.0.2-SNAPSHOT for the affected components.
> Error fix related to "NoSuchMethodError IGenericClient.registerInterceptor(IClientInterceptor)"

- a2d2-api/pom.xml
- cds-hook-model/pom.xml
- cds-hook-model/src/main/java/io/elimu/a2d2/cdsresponse/entity/CDSHookRequest.java
- cdshooks-wih/pom.xml
- cdshooks-wih/src/main/java/io/elimu/a2d2/cdshookswih/DeserializeCDSHooksRequestDelegate.java
- cdshooks-wih/src/test/java/io/elimu/a2d2/cdshooks_wih/DeserializeCDSHooksRequestDelegateTest.java
- core-dependencies/datafetch-service/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- core-dependencies/fhir-parse-util/src/main/java/io/elimu/a2d2/parsing/FhirParseUtil.java
- core-dependencies/fhir-parse-util/src/test/java/io/elimu/a2d2/parsing/FhirParseUtilTest.java
- fhir-query-helper-dstu2/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelper.java
- fhir-query-helper-dstu3/src/main/java/io/elimu/a2d2/cds/fhir/helper/dstu3/QueryingServerHelper.java
- fhir-query-helper-r4/src/main/java/io/elimu/a2d2/cds/fhir/helper/r4/QueryingServerHelper.java
- fhir-resource-wih/pom.xml
- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/DeserializeResourceDelegate.java
- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/FHIRDelegateHelper.java
- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/OperationOutcomeDelegate.java
- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/ResourceReadDelegate.java
- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/ResourceWriteDelegate.java
- fhir-resource-wih/src/main/java/io/elimu/a2d2/fhirresourcewih/SerializeResourceDelegate.java
- fhir-resource-wih/src/test/java/io/elimu/a2d2/fhir_resource_wih/ResourceReadDelegateTest.java
- fhir-resource-wih/src/test/java/io/elimu/a2d2/fhir_resource_wih/ResourceWriteDelegateTest.java
- ftl-transform-wih/pom.xml
- kie-based-services/pom.xml
- oauth-helpers/src/main/java/io/elimu/a2d2/OAuthHelper.java
- task-utilities/pom.xml
- task-utilities/src/main/java/io/elimu/task/fhir/FhirTaskEventListener.java
- task-utilities/src/main/java/io/elimu/task/fhir/r4/R4FhirTaskEventListener.java
Removes the need for HAPI fhir to be part of the webapp classloader, allowing different services to use different versions of FHIR
> Gt 699 hapi removal

- a2d2-api/pom.xml
Done with mitigate tomcat embed core, update version 9.0.56 to 9.0.62
Done with build and install and ran all integration test case
> mitigate tomcat embed websocket vulnerability

- cds-hook-services/pom.xml
- pom.xml
Done with mitigate the vulnerability by updating protobuf java version from 3.6.1 to 3.19.4
Done with build ran and successfully test it on local.
> Mitigated protobuf-java vulnerability by updating version

- core-wih/pom.xml
Done with mitigate spring core vulnerability in core with by updating version from 5.3.8 to 5.3.18
Done with build ran and test on the local
> Mitigated spring core vulnerability by updating version

- core-wih/pom.xml
- generic-helpers/pom.xml
- kie-based-services/pom.xml
- pom.xml
- task-utilities/pom.xml
Done with mitigate protobuf-java vulnerability by updating version from 3.6.1 to 3.19.4
> Mitigated protobuf vulernability from parent

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- pom.xml
- service-daos/pom.xml
When I generate a report from master, still we are getting spring core and spring tx vulnerability with `5.3.18` , So, I also update the spring boot version from 2.6.6 to 2.6.7, Done with mitigate vulnerability, Done with build, ran and test on local
> Updating spring version to mitigate spring vulnerability

- a2d2-api/pom.xml
- fhir-helpers/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/cache/CacheCleaner.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/cache/CacheUtil.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/cache/InMemoryCache.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/cache/JedisCache.java
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-r4/pom.xml
- generic-helpers/pom.xml
- oauth-helpers/pom.xml
- pom.xml
The in-memory cache was failing to cleanup after the allotted amount of time. Also, the jedis implementation needed to account for SSL and a password as an option for the connection
> Fixes for QSH in memory cache, and updates to jedis cache implementation

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- core-wih/pom.xml
- pom.xml
- service-daos/pom.xml
Mitigate spring boot by updating its version from 2.7.1 to 2.7.4
Mitigate Spring core by updating its version from 5.3.21 to 5.3.23
Done with build, run and  test it on local by running unit test cases and integration test cases of omnibus on local,
Also update same version in omnibus, Creating PR for same.
> Mitigate Spring related dependency

- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
These changes will allow us to not query the PlanDefinition twice, and use auth to fetch FHIR content
> CQL work item handler modifications to handle auth

- a2d2-api/pom.xml
- owasp-dependency-check-suppressions.xml
Done with mitigate tomcat-embed core from the repo, 
Done with test it by running omnibus on local run all the integration test case on local.
Also removed one extra suppression from suppression file of dependency check, which should not be there
Attached the latest report and screenshot of integration test cases
> Mitigate tomcat from 9.0.62 to 9.0.65

- cql-wih/pom.xml
- pom.xml
Done with updating version of jackson databind to 2.13.4,
Following versions get mitigate from report, 
jackson-databind-2.12.6.1.jar
jackson-databind-2.13.3.jar
jackson-databind-2.13.4.jar
but 2.13.4 is still available in report and jackson-databind-2.13.4 is latest version on maven report
Done with tested with by running with omnibus on local,
> MItigate jackson databind version by updating to 2.13.4

- pom.xml
Done with mitigate jbpm-bpmn2 7.71.0.Final by updating version kie-server-api from 7.71.0.Final to 7.73.0.Final, But still latest version is available in the report,
Done with build and test it by running with omnibus on local, 
Run integration test cases on local
> Mitigate jbpm-bpmn2 Vulnerability

- pom.xml
- sql/A2D2.SQL
- sql/A2D2_mysql.sql
Updated the version of kie from 7.71.0.final to 7.73.0.final,
Update the sql files which needs to be alter table
How it was tested
Test it by running it on local
Running the integration test cases and persitent integration test case pphtn program and pphtn-recommendation service by pointing local
> Mitigate jbpm bpmn2 vulnerability

- cds-hook-services/pom.xml
- pom.xml
When we generate a dependency check report so, we found this vulnerable with 2.3.0 so update version to 2.9.1
Done with test it by running omnibus on local. Ran the integration test cases
> Mitigate sshd-common by updating version to  2.9.1

- cds-hook-services/pom.xml
- pom.xml
When I generate a report found wildfly-elytron-audit@1.15.5
Done with mitigate wildfly-elytron-audit@1.15.5 by updating version to 2.0.0
Done with test it by running it with omnibus on local, and done with run all the integration test case on local
In this PR I down the version of sshd-common because, wildify using 2.7.0, and we have used latest, So, project is giving error while build, Its suggest to exclude or reduce the sshd-common version,
sshd-common-2.7.0 is not vulnerable.
> Mitigate wildfly-elytron-audit@1.15.5.Final by updating version to 2.0.0

- a2d2-api/pom.xml
- sms-wih/pom.xml
When we generate a report,found it aws-java-sdk-core vulnerable by updating version from 1.10.40  to 1.12.334
Done with run it with omnibus and ran integration test cases by pointing omnibus local
Update the joda-time version, Update the twilio version, twilio and aws-java-sdk-core both using different version of joda-time,
> Mitigate aws-java sdk core by updating version

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- pom.xml
- service-daos/pom.xml
When I generate report I found jackson databind vulnerable with high severity, Its coming from child of spring boot, Mitigate it by updating spring version and update the version which we are using keep same version as sping boot using internally,
> Mitigate jackson databind by updating spring-boot

- a2d2-api/pom.xml
When I generate a report I found tomcat-embed-core and tomcat-embed-websocker vulnerable with version 9.0.65. Update it to 9.0.68 to mitigate it, re-generate a report and its mitigate,
Run it with omnibus by updating tomcat version in omnibus, test all the integration test cases by pointing local,
> Mitigate tomcat embed core by updating version to 9.0.68

- cds-hook-services/pom.xml
- cdshooks-wih/pom.xml
- core-dependencies/datafetch-service/pom.xml
- core-dependencies/fhir-parse-util/pom.xml
- cql-wih/pom.xml
- fhir-helpers/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-r4/pom.xml
- fhir-resource-wih/pom.xml
- ftl-transform-wih/pom.xml
- kie-based-services/pom.xml
- oauth-helpers/pom.xml
- pom.xml
- task-utilities/pom.xml
Done with mitigate commons-text by exclude and added manually with updated version,
I try with update parent hapi-fhir to mitigate it, but its giving too much conflict its still available in the report from kie-based-services,
Mitigate it and ran it with omnibus by running on local..
> Mitigate commons-text by updating version

- owasp-dependency-check-suppressions.xml
This is a false positive and I’m going to add a suppression for it. The [mvnrepository.com](http://mvnrepository.com/) site shows no vulnerabilities in this version and the CVE (description below) mentions other/older versions.
Spring Security versions 5.3.x prior to 5.3.2, 5.2.x prior to 5.2.4, 5.1.x prior to 5.1.10, 5.0.x prior to 5.0.16 and 4.2.x prior to 4.2.16 use a fixed null initialization vector with CBC Mode in the implementation of the queryable text encryptor. A malicious user with access to the data that has been encrypted using such an encryptor may be able to derive the unencrypted values using a dictionary attack.
Ref: https://nvd.nist.gov/vuln/detail/CVE-2020-5408
> Add dependency-check suppression for spring-security-crypto

- owasp-dependency-check-suppressions.xml
Adding a suppression for this.
This vulnerability is not listed on mvnrepository [here](https://mvnrepository.com/artifact/org.springframework/spring-web/5.3.23).
The vulnerability cannot be mitigated by updating the dependency and Spring Boot will not be updated to resolve this. I’ve highlighted the reason below:
Pivotal Spring Framework through 5.3.16 suffers from a potential remote code execution (RCE) issue if used for Java deserialization of untrusted data. Depending on how the library is implemented within a product, this issue may or not occur, and authentication may be required. NOTE: the vendor's position is that untrusted data is not an intended use case. The product's behavior will not be changed because some users rely on deserialization of trusted data.
Ref: …
> Add dependency-check suppression for spring-web 5.3.23

- pom.xml
- task-utilities/pom.xml
When I generate a report I found protobuf-java is vulnerable with version 3.19.6 and update version to 3.21.8.
Done with mitigate it and test it with by running on local, Done with test it by running unit test case and integration test cases on local.
> Mitigate Protobuf-java by updating version to 3.21.8

- owasp-dependency-check-suppressions.xml
When I generate a report I found JBPM-BPM2 is vulnerable with latest version 7.73.0.final, The reason behind suppression is we are not using JBPM-BPM2 library for login into business centre console. We are using other services and models of JBPM-BPM2.
> Mitigate JBPM-BPMN2 in by doing suppression

- owasp-dependency-check-suppressions.xml
This vulnerability is comming from sshd-core (https://mvnrepository.com/artifact/org.apache.sshd/sshd-core), since we are not using Apache MINA SSHD (sshd-core),instead we are using sshd-common, we are not vulnerable to this hence adding suppression for it.
> Adds suppression for vulnerability wildfly-elytron

- owasp-dependency-check-suppressions.xml
I have remove old suppression cve from the owasp-dependency-check-report and in the report we found new one cve in a2d2 dependency check report and Added suppression for itv,
CVE-2022-1471 (OSSINDEX)
SnakeYaml's Constructor() class does not restrict types which can be instantiated during deserialization. Deserializing yaml content provided by an attacker can lead to remote code execution. We recommend using SnakeYaml's SafeConsturctor when parsing untrusted content to restrict deserialization.
[NVD - CVE-2022-1471](https://nvd.nist.gov/vuln/detail/CVE-2022-1471)
We are not using a reference of SnakeYaml's Constructor() in a2d2, So, we can suppress it, by removing old suppression.
> Adds suppression for snakeyaml vulnerability

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- pom.xml
- service-daos/pom.xml
When i generate a dependency check report I found it vulnerable, I Updated it to latest version but it still available in report, its asking for suppression, Then we can suppress it or not, So, I found any usage in a2d2,
So, directly remove and did testing by running omnibus on local.
Done with test it properly on local.
> Removing h2-database to mitigate we not found any usage of it

- a2d2-api/pom.xml
- core-wih/src/main/java/io/elimu/a2d2/corewih/ServiceRestAPIDelegate.java
- core-wih/src/main/java/io/elimu/a2d2/rulewih/DmnInvokeDelegate.java
- fhir-helpers/pom.xml
- fhir-query-helper-base/pom.xml
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/FetchCallRetry.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/FhirClientWrapper.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryBuilder.java
- fhir-query-helper-base/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelperBase.java
- fhir-query-helper-dstu2/pom.xml
- fhir-query-helper-dstu2/src/main/java/io/elimu/a2d2/cds/fhir/helper/QueryingServerHelper.java
- fhir-query-helper-dstu2/src/test/java/io/elimu/a2d2/cds/fhir/cache/test/QueryingServerHelperCacheTest.java
- fhir-query-helper-dstu2/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperTest.java
- fhir-query-helper-dstu3/pom.xml
- fhir-query-helper-dstu3/src/main/java/io/elimu/a2d2/cds/fhir/helper/dstu3/QueryingServerHelper.java
- fhir-query-helper-dstu3/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperCacheTest.java
- fhir-query-helper-r4/pom.xml
- fhir-query-helper-r4/src/main/java/io/elimu/a2d2/cds/fhir/helper/r4/QueryingServerHelper.java
- fhir-query-helper-r4/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/FhirTest.java
- fhir-query-helper-r4/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperCacheTest.java
- generic-helpers/pom.xml
- oauth-helpers/pom.xml
- oauth-helpers/src/test/java/io/elimu/a2d2/OAuthHelperTest.java
- pom.xml
Retry mechanishms added to CallREST work item handler and QueryingServerHelper REST invocations. Defaults to 3 retries, but can be configured through JVM properties, work item handler inputs, or QueryBuilder new methods, to have different retries and delays
> Retry mechanishms added

- kie-based-services/src/main/java/io/elimu/cdshookapi/service/RuntimeManagerHelper.java
In case the server is still starting up, this change makes sure the casting is done correctly (during startup, the instances of GenericService will be of instance GenericTempService, until replaced by GenericKieBasedService instance after initialization of service)
> RuntimeManagerHelper updates to check in case of non-finished startup

- owasp-dependency-check-suppressions.xml
- pom.xml
- We are not parsing any untrusted (user supplied supplied) YAML files.So adding suppression.
- SnakeYaml's Constructor() class does not restrict types which can be instantiated during deserialization. Deserializing yaml content provided by an attacker can lead to remote code execution. We recommend using SnakeYaml's SafeConsturctor when parsing untrusted content to restrict deserialization.
> suppressed vulnerability snake

- core-wih/pom.xml
Ran omnibus on local & verified SOFA & omnibus integration test cases passing
> Mitigate dependency vulnerability in a2d2:woodstox-core-5.1.0.jar

- kie-based-services/src/main/java/io/elimu/cdshookapi/service/RuntimeManagerHelper.java
Some possibly empty variables were not null-checked which lead to some of the APIs to query variables to fail
> ProcessInstanceHelper null check

- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericKieBasedService.java
when the buildRequest method is called to build a ServiceRequest object from HttpServletRequest, it always stores header name as lower case. so updated the `getClient` method to get header from key authorization 
- Tested locally by passing auth header containing tenant.
> updated GetClient method to return client from jwt token 

- cql-wih/pom.xml
- fhir-helpers/pom.xml
Mitigated hl7-fhir-r5 vulnerability
> mitigated vulnerability hl7-fhir-r5

- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericKieBasedService.java
In order to use the configApi provided client in the OAuth token, we need to pass it as a process variable. This PR takes care of that
> configApiClient variable population from generic service

- kie-based-services/src/main/java/io/elimu/serviceapi/config/ConfigAPIUtil.java
This change makes the ConfigAPIUtil call timeout configurable through JVM properties, defaulting to 10 seconds
> update for config api call timeout

- pom.xml
- There is a bug in the dependency-check-maven dependency that we use to generate vulnerability reports that is causing a lot of new, and HIGH severity, vulnerabilities to appear in our reports that are false positives.
> Updated dependency-check-maven version

- owasp-dependency-check-suppressions.xml
- plexus-utils-3.5.1.jar vulnerability appearing in the report is due to a bug in the dependency-check-maven version used in a2d2
> revert suppression plexus utils

- kie-based-services/pom.xml
- owasp-dependency-check-suppressions.xml
Mitigated cxf-rt-bindings-soap-3.4.10.jar vulnerability
Adding suppression for this vulnerability because we are not using RPCRouterServlet of Apache SOAP in  a2d2, https://nvd.nist.gov/vuln/detail/CVE-2022-40705
> Mitigate dependency cxf-rt-bindings-soap-3.4.10.jar

- cds-hook-model/src/main/java/io/elimu/a2d2/process/ServiceUtils.java
- fhir-query-helper-dstu2/src/test/java/io/elimu/a2d2/cds/fhir/helper/test/QueryingServerHelperTest.java
- fhir-resource-wih/src/test/java/io/elimu/a2d2/fhir_resource_wih/ResourceReadDelegateTest.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericService.java
- kie-based-services/src/main/java/io/elimu/genericapi/service/GenericTempService.java
- kie-based-services/src/main/java/io/elimu/serviceapi/config/JWTAuthUtil.java
- service-daos/src/main/java/io/elimu/service/models/ServiceInfo.java
These changes allow us to determine as early as possible the customers, packages and service types of deployed services. Needed for Omnibus to determine which paths are open to the public.
> Changes needed for dynamically determining auth properties

- cql-wih/src/main/java/io/elimu/a2d2/cql/CardCreator.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
There was a significant change needed in the way cards were created based on the execution of a PlanDefinition, defined in this graph: 
This meant changing the way actions are generated in the output of DecoratedPlanDefinitionProcessor, and in how that is translated to a Card by CardCreator
This was tested by executing the different unit tests available in CqfInlineWIHTest to validate older output structures were respected
> Card structure generation formatting

- cql-wih/src/main/java/io/elimu/a2d2/cql/CardCreator.java
- cql-wih/src/main/java/io/elimu/a2d2/cql/DecoratedPlanDefinitionProcessor.java
- cql-wih/src/test/java/io/elimu/a2d2/cql/CqfInlineWIHTest.java
There were problems with the caching mechanisms for CQL operations which were causing results from one patient request to be used for another patient. This correction fixes that issue
> CQL caching issues fix

- owasp-dependency-check-suppressions.xml
Mitigated vulnerability org.hl7.fhir.r5-5.5.7.jar by adding suppression
> Mitigate dependency vulnerability org.hl7.fhir.r5-5.5.7.jar

- cql-wih/src/main/java/io/elimu/a2d2/cql/PlanDefCdsInlineWorkItemHandler.java
Moving the setHttpClient method a few lines after the setConnectTimeout and setSocketTimeout calls prevents HttpClient from being reset on the underlying implementation
> CachingHttpClient re-enabling by putting it after the rest of the timeout configurations

- owasp-dependency-check-suppressions.xml
Mitigated vulnerability commons-beanutils-1.9.3.jar by adding suppression
> Mitigate dependency vulnerability commons-beanutils-1.9.3.jar

- owasp-dependency-check-suppressions.xml
Mitigated dependency vulnerability plexus-cipher-2.0.jar by adding suppression
> Mitigate dependency vulnerability plexus-cipher-2.0.jar

- owasp-dependency-check-suppressions.xml
Mitigated dependency vulnerability plexus-component-annotations-2.1.0.jar by adding suppression
> Mitigate dependency vulnerability plexus-component-annotations-2.1.0.jar

- owasp-dependency-check-suppressions.xml
Mitigated dependency vulnerability plexus-classworlds-2.6.0.jar by adding suppression
> Mitigate dependency vulnerability plexus-classworlds-2.6.0.jar

- owasp-dependency-check-suppressions.xml
Suppressed the vulnerability for `json-20230227.jar`
This vulnerability appears due to the `JSONTokener.next()` which leads to the "Parsing untrusted input could then potentially lead to OutOfMemoryError even for quite small input strings."
We have not used the **JSONTokener.next()** in the code, so we are not directly vulnerable to this vulnerability.
https://nvd.nist.gov/vuln/detail/CVE-2023-5072
https://github.com/stleary/JSON-java/issues/758
> Mitigate dependency vulnerability in a2d2: json-20230227.jar

- a2d2-api/pom.xml
- cds-hook-services/pom.xml
- kie-based-services/pom.xml
- pom.xml
- service-daos/pom.xml
- Updated the `tomcat-embed-core` and `tomcat-embed-websocket` dependency to **9.0.82** version
- Successfully mitigated the `tomcat-embed-core` vulnerability.
- Ran mvn site on local & verified vulnerability is mitigated successfully.
> Mitigate dependency vulnerability in a2d2:tomcat-embed-core 9.0.75

- a2d2-api/pom.xml
- Updated the `bcprov-jdk18on` dependency  to 1.74 version
- Successfully mitigated the `bcprov-jdk15on` vulnerability.
- Ran mvn site on local & verified vulnerability is mitigated successfully.
> Mitigate dependency vulnerability in a2d2: bcprov-jdk15on-1.69.jar

- a2d2-api/pom.xml
Mitigated logback-core-1.2.9.jar vulnerability by updating version to 1.2.13.
> Mitigate dependency vulnerability in a2d2: logback-core-1.2.9.jar

- owasp-dependency-check-suppressions.xml
Mitigated vulnerability logback-core-1.2.12.jar by adding suppression
- Verified by generating report by mvn site.
> Mitigate dependency vulnerability in a2d2: logback-core-1.2.12.jar

- owasp-dependency-check-suppressions.xml
- Mitigated vulnerability `logback-classic-1.2.10.jar` by adding suppression.
- The vulnerability is due to serialization vulnerability in logback receiver component allows an attacker to mount a Denial-Of-Service attack by sending poisoned data.
- This dependency `logback-classic-1.2.10.jar`  comes under spring-boot-starter so we  are not directly vulnerable for this dependency.
- When updated spring-boot-starter to the latest version the `logback-classic` vulnerability still exists so I have added the suppression
-  I have added the links to reference,
- [News](https://logback.qos.ch/news.html#1.3.12) 
- [NVD - CVE-2023-6378](https://nvd.nist.gov/vuln/detail/CVE-2023-6378)
- [NVD - CVE-2023-6481](https://nvd.nist.gov/vuln/detail/CVE-2023-6481) …
> Mitigate dependency vulnerability in a2d2: logback-classic-1.2.10.jar

- pom.xml
- Updated the `netty-version` to 4.1.104.Final
- Successfully mitigated the netty-transport vulnerability.
- Ran mvn site on local & verified vulnerability is mitigated successfully.
[dependency-check-report.pdf](https://github.com/elimuinformatics/a2d2/files/13803711/dependency-check-report.2.pdf)
> Mitigate dependency vulnerability in a2d2: netty-transport-4.1.94.Final.jar

- a2d2-api/pom.xml
- Updated the postgresql version to 42.7.3
- Successfully mitigated the postgresql vulnerability.
- Ran mvn site on local & verified vulnerability is mitigated successfully.
> Mitigate dependency vulnerability in a2d2: postgresql-42.5.1.jar
